name: "Update Language Source"
description: "Update Source files for the scientific python project"
author: "@goanpeca"
inputs:
  source-repo:
    description: "Source repository"
    required: true
  source-folder:
    description: "Source folder"
    default: ""
  source-ref:
    description: "Source reference"
    default: "main"
  translations-repo:
    description: "Translations repository"
    default: ""
  translations-folder:
    description: "Translations folder"
    default: ""
  translations-ref:
    description: "Translations reference"
    default: "main"
  gpg_private_key:
    description: "TODO"
    required: true
  passphrase: 
    description: "TODO"
    required: true    
  github-token:
    description: "TODO"
    required: true
outputs:
  todo:
    description: "TODO"
# runs:
#   using: "docker"
#   image: "Dockerfile"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        repository: 'Scientific-Python-Translations/content-sync'
    - name: Import GPG key
      id: import-gpg
      uses: crazy-max/ghaction-import-gpg@v4
      with:
        gpg_private_key: ${{ inputs.GPG_PRIVATE_KEY }}
        passphrase: ${{ inputs.PASSPHRASE }}
        git_user_signingkey: true
        git_commit_gpgsign: true
        git_config_global: true
    - name: Configure commit signing
      shell: bash
      run: |
          git config --global user.email "${{ steps.import-gpg.outputs.email }}"
          git config --global user.name "${{ steps.import-gpg.outputs.name }}"
    - name: Configure python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12' # '3.x'
    - name: Run scripts
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        INPUT_SOURCE-REPO: ${{ inputs.SOURCE-REPO }}
        INPUT_SOURCE-FOLDER: ${{ inputs.SOURCE-FOLDER }}
        INPUT_SOURCE-REF: ${{ inputs.SOURCE-REF }}
        INPUT_TRANSLATIONS-REPO: ${{ inputs.TRANSLATIONS-REPO }}
        INPUT_TRANSLATIONS-FOLDER: ${{ inputs.TRANSLATIONS-FOLDER }}
        INPUT_TRANSLATIONS-REF: ${{ inputs.TRANSLATIONS-REF }}
        GPG_NAME: ${{ steps.import-gpg.outputs.email }}
        GPG_EMAIL: ${{ steps.import-gpg.outputs.name }}
      run: |
        python -m pip install --upgrade pip
        python -m pip install requests pygithub
        python main.py
