name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      # - name: Import GPG key
      #   id: import-gpg
      #   uses: crazy-max/ghaction-import-gpg@v4
      #   with:
      #     gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
      #     passphrase: ${{ secrets.PASSPHRASE }}
      #     git_user_signingkey: true
      #     git_commit_gpgsign: true
      #     git_config_global: true
      # TODO: Move this to the python script or a composite action?
      # - name: Configure commit signing
      #   run: |
      #       git config --global user.email "${{ steps.import-gpg.outputs.email }}"
      #       git config --global user.name "${{ steps.import-gpg.outputs.name }}"
      - name: Self test
        id: selftest
        uses: Scientific-Python-Translations/content-sync@main
        env:
            TOKEN: ${{ secrets.TOKEN }}
        with:
          source-repo: "scientificpythontranslations/pandas"
          source-folder: "pandas/web/pandas/"
          source-ref: "test-trans"
          translations-repo: "scientificpythontranslations/pandas-translations"
          translations-folder: "pandas-translations/content/en/"
          translations-ref: "main"
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          token: ${{ secrets.TOKEN }}
