name: Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Test action
        uses: Scientific-Python-Translations/content-sync@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          source-repo: "scientificpythontranslations/pandas"
          source-folder: "pandas/web/pandas/"
          source-ref: "test-trans"
          translations-repo: "scientificpythontranslations/pandas-translations"
          translations-folder: "pandas-translations/content/en/"
          translations-ref: "main"
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          token: ${{ secrets.TOKEN }}
